name: Generate Checkin Charts

on:
  schedule:
    - cron: '0 0 * * *'  # Run the workflow every day at midnight (12:00 AM)

  workflow_dispatch:   # Add this section to enable manual triggering
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: false

jobs:
  create-checkin-chart:
    # if: ${{ github.event.issue.user.login == github.actor && contains(github.event.issue.title, 'notion-ci') }}
    # if: ${{ contains(github.event.issue.title, 'checkin-chart-ci') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Workflows are only triggered when commits (and tags I think, but it would need to be tested) are created pushed using a Personal Access Token (PAT).
        # ref: https://github.com/EndBug/add-and-commit/issues/311#issuecomment-948749635
        token: ${{ secrets.CHECKIN_CHART_TOKEN || 'changeme' }}

    - name: Create chart from google sheet
      uses: phuang07/checkin-chart@main
      with:
          IMG_DIR: 'static/images/checkin_charts'
          GOOGLE_SHEET_CRED: ${{ secrets.GOOGLE_SHEET_CRED }}
    - name: push to github
      uses: EndBug/add-and-commit@v7
      with:
        branch: hugo
        message: 'Generate Checkin Charts'
