name: Generate Checkin Charts

on:
  schedule:
    - cron: '* * * * *'  # Run the workflow every minute

jobs:
  create-checkin-chart:
    # if: ${{ github.event.issue.user.login == github.actor && contains(github.event.issue.title, 'notion-ci') }}
    if: ${{ contains(github.event.issue.title, 'checkin-chart-ci') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Workflows are only triggered when commits (and tags I think, but it would need to be tested) are created pushed using a Personal Access Token (PAT).
        # ref: https://github.com/EndBug/add-and-commit/issues/311#issuecomment-948749635
        token: ${{ secrets.CHECKIN_CHART_TOKEN || 'changeme' }}

    - name: Create chart from google sheet
      uses: phuang07/checkin-chart@main
      with:
          IMG_DIR: 'statics/images/checkin_charts/'
          GOOGLE_SHEET_CRED: ${{ secrets.GOOGLE_SHEET_CRED }}
    - name: push to github
      uses: EndBug/add-and-commit@v7
      with:
        branch: hugo
        message: 'Generate Checkin Charts'
